name: CI-CD Build and Deploy Docker Image

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            docker stop frontend-app || true
            docker rm frontend-app || true

           sudo rm -rf devops || true
        git clone https://github.com/mbhavanasri03-png/devops.git
        cd "devops/CI-CD Pipeline Project/Source Code"
        

            docker build -t frontend-app .
            docker run -d -p 80:80 --name frontend-app frontend-app

